version: '3.4'

services:
  migrations:
    build:
      context: ../../
      dockerfile: templates/service/database/Dockerfile
    depends_on:
      - sqlserver
    environment:
      - IdentityServer_DB=FeedBack_Identity
      - FeedBack_DB=FeedBack_ModuleDb
      - SA_PASSWORD=yourStrong(!)Password
