# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

services:
  feedbackworkerservice:
    image: feedbackworkerservice
    build:
      context: .
      dockerfile: src/FeedbackWorkerService/Dockerfile
    ports:
      - 5000:5000
